import os

SECRET_KEY = os.getenv("SECRET_KEY", "Super secret key")
SECURITY_ALGORITHM = os.getenv("SECURITY_ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES","30")